language: csharp  
services:
  - docker
sudo: required  
mono: none
dotnet: 2.2
before_script:
  - dotnet restore ./Rsoi.Net/
script:  
  - dotnet test ./Rsoi.Net/ -c Release

#deploy:
#  provider: script
#  script: 
#  on:
#    all_branches: true