sudo: true
dist: trusty

jobs:
  include:
    #- stage: build docker image
    #  script:
    #  - docker login -u=$DOCKER_USERNAME -p=$DOCKER_PASSWORD 
    #  - docker build -t sych474/$SERVICE_NAME:1 ./Rsoi.Net/CharactersHub
    #  - docker push sych474/$SERVICE_NAME:1

    - stage: deploy to remote
      script: sudo ./DeployScripts/deploy.sh