version: '3.2'

services:
    characters_hub:
      image: sych474/rsoi_characters_hub:latest
      ports:
        - "80:5000"
      depends_on:
        - database
      networks:
        - net
        
    database: 
      image: postgres
      ports:
        - "5432:5432"
      networks:
        - net

networks:
  net:
