version: '3.2'

services:
    characters_hub:
      build: ./Rsoi.Net/CharactersHub/
      ports:
        - "5000:80"
      depends_on:
        - database
      networks:
        - net
    database: 
      image: postgres
      port:
        - "5432:5432"
      networks:
        - net

networks:
  net: