version: '3.2'

services:
    characters_hub:
      image: webber1580/characters_hub:1
      ports:
        - "5000:80"
      depends_on:
        - database
      networks:
        - net
        
    database: 
      image: postgres
      ports:
        - "5432:5432"
      networks:
        - net

networks:
  net:
